title: root💀muzec-sec:~#
#description: Try Harder!!!
show_downloads: false
show_repo: false
theme: jekyll-theme-hacker

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
# Includes an icon in the footer
footer-links:
  github: muzec0318
  twitter: muzec_saminu
